### ISSUE TITLE
Request to change package name

### ISSUE THREAD

**Issue by Azeezkadiri** [krshkun/azelf#3]
### Description

You published a the package without changing the name **"Trevenant"** from the template. 
Could you please chang the name of the package as soon as possible

**Thanks**

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/krshkun/azelf/blob/main/CODE_OF_CONDUCT.md)

**Comment by krshkun** [comment]
Thanks for the contribution!
